### ISSUE TITLE
AttributeError: Debugger instance has no attribute 'bend' 

### ISSUE THREAD

**Issue by mgedmin** [jaredly/vim-debug#3]
After some fooling around with

  :Dbg b
  (timeout)
  :Dbg quit
  :Dbg -
  (timeout)
  :Dbg quit
  :Dbg .

I got an error message that I dismissed by accident without being able to read.  Now I cannot :Dbg quit -- I get this traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mg/.vim/plugin/vim_debug/commands.py", line 44, in debugger_cmd
    cmd['function'](*args)
  File "/home/mg/.vim/plugin/vim_debug/new_debugger.py", line 187, in quit
    self.bend.close()
AttributeError: Debugger instance has no attribute 'bend'
```

":Dbg ." now doesn't work either -- prints the usage message -- so there's no obvious way to debug anything without restarting vim.

**Comment by pbassut** [comment]
+1

**Comment by pbassut** [comment]
So, I tried to find out what was happening in the code and looks like pydbgp.py couldn't initialize due a environment variable that it didn't recognized.

After running the following command(e.g. setting the required environment variables), it worked:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
