### ISSUE TITLE
Symbol not found: _PyByteArray_Type

### ISSUE THREAD

**Issue by communityds-leons** [jaredly/vim-debug#35]
Having just re-installed Vim from source in OS X:

Vim version: 8.0.1848
OS X version: 10.13.4
Python version: 3.6.4 (via pyenv)
Vim package management: Vim >= 8 internal

Other plugins are loading fine. When I try to load the vdebug plugin, either by placing in a `~/.vim/pack/*/start` folder or via `:packadd vdebug`, I get the following error:

```
Error detected while processing /Users/leons/.vim/pack/plugins/opt/vdebug/plugin/vdebug.vim:                                                             
line   39:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/leons/.vim/pack/plugins/opt/vdebug/pythonx/start_vdebug.py", line 8, in <module>
    import vdebug.debugger_interface
  File "/Users/leons/.vim/pack/plugins/opt/vdebug/pythonx/vdebug/debugger_interface.py", line 3, in <module>
    from . import breakpoint
  File "/Users/leons/.vim/pack/plugins/opt/vdebug/pythonx/vdebug/breakpoint.py", line 1, in <module>
    import base64
  File "/Users/leons/.pyenv/versions/3.6.4/lib/python3.6/base64.py", line 10, in <module>
    import struct
  File "/Users/leons/.pyenv/versions/3.6.4/lib/python3.6/struct.py", line 13, in <module>
    from _struct import *
ImportError: dlopen(/Users/leons/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_struct.cpython-36m-darwin.so, 2): Symbol not found: _PyByteArray_Type
  Referenced from: /Users/leons/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_struct.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/leons/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_struct.cpython-36m-darwin.so
line  114:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vdebug' is not defined
Error detected while processing function Vdebug_load_options:
line    8:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'debugger' is not defined
Error detected while processing function Vdebug_load_keymaps:
line   22:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'debugger' is not defined
Press ENTER or type command to continue
```

Of note, `:python3` commands work fine in Vim, though `:python` commands do not. Does vdebug require both to be working?

**Comment by communityds-leons** [comment]
duplicate
